from pathlib import Path
import json,hashlib,os,re
N=Path(__file__).resolve().parent;P=N.parents[1];W=P.parents[4];A=W/'apps/gnu-diffutils';assert os.environ.get('LIBX_UPDATE_WORKSPACE')==str(W);h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();example=A/'src/content/docs/v3-12/en/01-guide/01-overview.md';line=next(x for x in example.read_text().splitlines()if x.startswith('documentContext: '));context=json.loads(line.removeprefix('documentContext: '));assert len(context)==1 and context[0]['kind']=='source';raw=context[0]['html'];assert 'Modified6October2026' in raw
raw=raw.replace('Comparison and Output Formats — Overview and Chapters 1–4','Comparison and Merging — Overview and Chapters 1–9',1).replace('比較と出力書式 — 概要・第1〜4章','比較とマージ — 概要・第1〜9章',1);entry='<p>7 October 2026: Libx GNU diffutils 3.12 Comparison and Merging — Overview and Chapters 1–9 / Libx GNU diffutils 3.12 比較とマージ — 概要・第1〜9章. Modification author and publisher: Libx. Added complete chapters 5–9, with independent Japanese translation and static original examples. The previously published Overview and Chapters 1–4 text is retained; original archive, permission, authors and full English GFDL are preserved.</p>'
assert raw.count('</section>')==1;context[0]['html']=raw.replace('</section>',entry+'</section>');(N/'DOCUMENT_CONTEXT.json').write_text(json.dumps(context,ensure_ascii=False,indent=2)+'\n');rows=[]
for row in json.loads((N/'CANONICAL_BINDING.json').read_text())['rows']:
 p=W/row['path'];s=p.read_text();assert 'documentContext:'not in s;front,body=s.split('---',2)[1:];front=front.strip()+'\ndocumentId: '+json.dumps('gnu-diffutils:3.12:'+Path(row['id']).stem)+'\nlicenseSource: "gnu-diffutils-manual"\ntoc: {"maxLevel": 4}\ndocumentContext: '+json.dumps(context,ensure_ascii=False)+'\n';out='---\n'+front+'---'+body
 for dest in [p,A/'src/content/docs/v3-12'/row['language']/row['id'],A/'public/source/v3-12/edited'/row['language']/row['id']]:dest.write_text(out)
 assert out.split('---',2)[2]==body;rows.append({'id':row['id'],'language':row['language'],'canonicalSHA256':h(p),'bodyUnchanged':True})
p=A/'src/config/project.config.jsonc';config=json.loads(p.read_text());config['translations']['en'].update(displayName='GNU diffutils Comparison and Merging',displayDescription='GNU diffutils3.12 Overview and complete chapters1–9');config['translations']['en']['categories']['guide']='Comparison and merging';config['translations']['ja'].update(displayName='GNU diffutils 比較とマージ',displayDescription='GNU diffutils3.12概要と第1〜9章全文の原文と独自日本語訳');config['translations']['ja']['categories']['guide']='比較とマージ';source=config['licensing']['sources'][0];source['name']=source['name'].replace('chapters1–4','chapters1–9');source['provenanceNotes'][0]['en']=source['provenanceNotes'][0]['en'].replace('chapters1–4','chapters1–9');source['provenanceNotes'][0]['ja']=source['provenanceNotes'][0]['ja'].replace('第1〜4章','第1〜9章');source['provenanceNotes']=[z for z in source['provenanceNotes']if not z['en'].startswith('Chapters5–9 were added')];source['provenanceNotes'].append({'en':'Chapters5–9 were added on7October2026. Existing Overview and Chapters1–4 retain their previous preferred text and modification history.','ja':'2026年10月7日に第5〜9章を追加しました。既存の概要・第1〜4章の定本文と変更履歴は保持しています。'});p.write_text(json.dumps(config,ensure_ascii=False,indent=2)+'\n');(N/'CONTEXT_BINDING.json').write_text(json.dumps({'status':'saved-context-body-unchanged','documents':38,'contextSHA256':h(N/'DOCUMENT_CONTEXT.json'),'siteConfigSHA256':h(p),'rows':rows,'meaningReview':'Body review retained; commoncontext separate reading pending'},indent=2)+'\n');print('New38notice/context added;old87MD untouched;sourcekit pending')
