"""Save formal notice/configuration drafts. Does not create or approve an app."""
from pathlib import Path
from bs4 import BeautifulSoup
import json
N=Path(__file__).resolve().parent
C=json.loads((N/'CANDIDATE_DRAFT.json').read_text())
s=BeautifulSoup((N/'source/derived-manual.html').read_text(),'html.parser')
top=s.find(id='Top');copying=''.join(str(p)for p in top.find_all(['p','blockquote'],recursive=False))
fdl=s.find(id='GNU-Free-Documentation-License');assert fdl
for a in fdl.select('a[href]'):
 if a['href'].startswith('#'):a['href']='/docs/gnu-gzip/source/v1-15/manual.html'+a['href']
title='Libx GNU gzip 1.15 User Guide / Libx GNU gzip 1.15 利用ガイド'
notice='<section class="gnu-gzip-notices"><h3>'+title+'</h3><p>Original author: Jean-loup Gailly. Original publisher: Free Software Foundation. Modification author and publisher: Libx.</p>'+copying+'<p>Copyright © 2026 Libx, for editing and independent Japanese translation. This modified guide is available under GNU Free Documentation License 1.3 or later, with no Invariant Sections, Front-Cover Texts, or Back-Cover Texts. No cover texts or invariant sections have been added.</p><h3>History / 履歴</h3><p>Original: GNU Gzip: General file (de)compression; version 1.15; document revision 3 January 2026; author Jean-loup Gailly; publisher Free Software Foundation. Source: gzip-1.15.tar.xz, SHA256 '+C['sourceArchive']['sha256']+'.</p><p>2026: '+title+'. Modification author and publisher: Libx. Complete overview and chapters 1–7 in editable Markdown, static examples and independent unofficial Japanese translation. Original copyright, permission and whole English license retained. Modified 6 October 2026.</p></section>'
(N/'drafts/notice-context.json').write_text(json.dumps([{'kind':'source','html':notice+'<details class="gnu-gzip-license"><summary>Original English GNU Free Documentation License / 原英語GFDL全文</summary>'+str(fdl)+'</details>'}],ensure_ascii=False,indent=2)+'\n')
prefix='/docs/gnu-gzip/source/v1-15/'
links=[('manual.html','Fixed complete original manual','固定原文マニュアル全文'),('original/gzip-1.15.tar.xz','Unchanged original source archive','未変更の原著ソース配布物'),('original/doc/gzip.texi','Original editable Texinfo','編集可能な原Texinfo'),('original/doc/gzip.info','Original Info manual','原Infoマニュアル'),('source.zip','Editable source and rebuild kit','編集用原稿・再生成キット'),('SOURCE_README.md','Source and license notes','原稿とライセンスの案内')]
config={'paths':{'baseUrlPrefix':'/docs','projectSlug':'gnu-gzip','siteUrl':'https://libx.dev'},'language':{'default':'en','supported':['en','ja'],'displayNames':{'en':'English','ja':'日本語'}},'translations':{'en':{'displayName':'GNU gzip User Guide','displayDescription':'GNU gzip 1.15 complete user guide','categories':{'guide':'User guide','reference':'Original English notices'}},'ja':{'displayName':'GNU gzip 利用ガイド','displayDescription':'GNU gzip 1.15の全利用ガイドの原文・独自日本語訳','categories':{'guide':'利用ガイド','reference':'原英語の通知'}}},'versioning':{'versions':[{'id':'v1-15','name':'1.15','date':'2026-10-06T00:00:00Z','isLatest':True}]},'licensing':{'defaultSource':'gnu-gzip-manual','showAttribution':True,'sourceLanguage':'en','sources':[{'id':'gnu-gzip-manual','name':'GNU gzip 1.15 manual, Overview and complete chapters 1–7','author':'Jean-loup Gailly / Free Software Foundation','license':'GFDL1.3-or-later','licenseUrl':prefix+'manual.html#GNU-Free-Documentation-License','sourceUrl':'https://www.gnu.org/software/gzip/manual/','provenanceNotes':[{'en':'This unofficial Libx guide includes the complete overview and chapters 1–7 of GNU gzip 1.15. The original English license is retained; the concept index is available in the fixed complete original manual, Info and Texinfo originals. Examples and output are displayed statically.','ja':'Libxによる非公式ガイドです。GNU gzip 1.15の原文概要・通知と第1〜7章全文を提供します。原英語のライセンスを保持し、概念索引は固定全文の英語マニュアル・Info・Texinfo原稿で参照できます。例と出力は静的に表示します。'},{'en':'Original copyright, permission, author, publisher, History and the whole original English GFDL are retained below. There are no Invariant Sections or Cover Texts.','ja':'原著作権・許諾・著作者・発行者・履歴・原英語GFDL全文を以下に保持しています。不変節・表紙文言はありません。'},{'en':'The document revision is 3 January 2026; the release date is 20 September 2026; the site date is acquisition 6 October 2026. Source fixed to the 1.15 archive SHA256 '+C['sourceArchive']['sha256']+'. Original sources are unmodified.','ja':'文書改訂日は2026年1月3日、リリース日は2026年9月20日、サイト版の日付は取得日の2026年10月6日です。原著1.15配布物SHA256 '+C['sourceArchive']['sha256']+'に固定しています。原著ソースは変更していません。'}],'attributionLinks':[{'url':prefix+p,'label':{'en':en,'ja':ja}}for p,en,ja in links]}]}}
(N/'drafts/project.config.jsonc').write_text(json.dumps(config,ensure_ascii=False,indent=2)+'\n')
print('GNU gzip complete notice/English license/History/config drafts saved; formal adoption pending')
