from pathlib import Path
import json,re,hashlib
root=Path('/Users/dolphilia/github/libx');w=Path('/private/tmp/libx-xxhash-import-20261003');note=root/'docs/notes/document-import/xxhash/v0-8-4';mp=json.load(open(note/'CONTENT_MAP.json'));it=next(x for x in mp['items']if x['slug']=='02-api/15-group___x_x_h3__impl');s=(w/it['canonical']).read_text();body,foot=s.split('## Source and notices');a=body.index('<div');prefix=body[:a];body=body[a:]
m={
'&#10;Macros':'&#10;マクロ','&#10;Typedefs':'&#10;型定義','&#10;Functions':'&#10;関数','&#10;Variables':'&#10;変数','Detailed Description':'詳細説明','Macro Definition Documentation':'マクロ定義の説明','Function Documentation':'関数の説明','Variable Documentation':'変数の説明','Value:':'値：','Initial value:':'初期値：','Definition':'定義',
'Calculates 64/128-bit seeded variant of XXH3 hash of':'XXH3のシード付き64/128ビット版で、次の入力のハッシュを計算します：','Parameters':'引数','The block of data to be hashed, at least':'ハッシュを計算するデータブロック。サイズは少なくとも','bytes in size.':'バイト必要です。','The length of':'次のデータの長さ：',', in bytes.':'（バイト単位）。','The secret data.':'シークレットのデータ。','The 64-bit seed to alter the hash result predictably.':'ハッシュ結果を予測可能な形で変化させる64ビットのシード。',
'These variants generate hash values using either:':'これらの版は、次のいずれかを使用してハッシュ値を生成します：','for "short" keys (&lt;':'：「短い」キーの場合（&lt;','= 240 bytes)':'= 240バイト）','for "large" keys (&gt;=':'：「大きい」キーの場合（&gt;=',').':'）。',
'This generally benefits speed, compared to':'これは一般に、次の版に比べて速度面で有利です：','or':'または',
'has to generate the secret on the fly for "large" keys. It\'s fast, but can be perceptible for "not so large" keys (&lt; 1 KB).':'は「大きい」キーの場合、シークレットをその場で生成する必要があります。この処理は高速ですが、「それほど大きくない」キー（1 KB未満）では、そのコストが目立つことがあります。',
'has to generate the masks on the fly for "small" keys, which requires more instructions than _withSeed() variants. Therefore, _withSecretandSeed variant combines the best of both worlds.':'は「小さい」キーの場合、マスクをその場で生成する必要があり、_withSeed()版よりも多くの命令を必要とします。そのため、_withSecretandSeed版は両方の長所を組み合わせています。',
'When':'次の条件の場合：','has been generated by':'が次の関数で生成されているとき：',', this variant produces':'この版は、','exactly':'まったく','the same results as':'同じ結果を次の版と生成します：',
'variant, hence offering only a pure speed benefit on "large" input, by skipping the need to regenerate the secret for every large input.':'。つまり、大きい入力ごとにシークレットを再生成する必要がなくなり、「大きい」入力では純粋に速度面の利点だけを得られます。',
'Another usage scenario is to hash the secret to a 64-bit hash value, for example with':'別の使い方として、たとえば次の関数でシークレットの64ビットハッシュ値を計算し：',
', which then becomes the seed, and then employ both the seed and the secret in _withSecretandSeed(). On top of speed, an added benefit is that each bit in the secret has a 50% chance to swap each bit in the output, via its impact to the seed.':'その値をシードとして、_withSecretandSeed()にシードとシークレットの両方を渡す方法があります。速度に加え、シークレットの各ビットがシードに影響することで、出力の各ビットを50%の確率で反転させるという利点があります。',
'This is not guaranteed when using the secret directly in "small data" scenarios, because only portions of the secret are employed for small data.':'「小さいデータ」でシークレットを直接使用する場合は、この性質は保証されません。小さいデータでは、シークレットの一部分しか使用されないためです。','.':'。'}
parts=re.split(r'(<[^>]*>)',body);used=[]
for i in range(0,len(parts),2):
 x=parts[i].strip()
 if x in m:parts[i]=parts[i].replace(x,m[x]);used.append(x)
assert set(m)==set(used),set(m)-set(used)
body=''.join(parts)
titles={'Generate the same secret as the _withSeed() variants.':'_withSeed()版と同じシークレットを生成します。','Calculates 64-bit unseeded variant of XXH3 hash of input.':'inputのXXH3ハッシュをシードなし64ビット版で計算します。'}
for a,b in titles.items():body=body.replace('title="'+a+'"','title="'+b+'"')
# Improve the description while retaining the inline-code order and all tags.
body=re.sub(r'XXH3のシード付き64/128ビット版で、次の入力のハッシュを計算します： (<code class="param">data</code>)。',r'\1のXXH3ハッシュをシード付き64/128ビット版で計算します。',body)
prefix='''---
title: "XXH3の実装"
licenseSource: "xxhash-api"
---

## 固定した上流原文に対する編集注記

以下の生成本文は原文の構造を保持しています。この注記は、固定した0.8.4のヘッダー実装との静的比較に基づくLibxの補足であり、上流原文を訂正したものではありません。

- **secret-seed-240-boundary**：XXH3_64bits_withSecretandSeedとXXH3_128bits_withSecretandSeedの固定実装は、入力が240バイト以下ならシードと既定のシークレットを使用し、240バイトを超えるなら渡されたシークレットを使用します。原文の説明は異なる境界を使っています。この観察は実装と仕様の静的比較に基づき、この境界に関する数値ハッシュ試験は行っていません。

マクロ値のコメントの意味：`nothing`は「何もない」、`disabled`は「無効」、`minimum XXH3_SECRET_SIZE_MIN`は「最小値はXXH3_SECRET_SIZE_MIN」、`nb of secret bytes consumed at each accumulation`は「各蓄積処理で消費するシークレットのバイト数」です。コメントとコードは原文どおり保持しています。

[固定した上流ヘッダー](https://github.com/Cyan4973/xxHash/blob/c87183a77d67f7d37e3d2d1b7eaac5e7c695e4f0/xxhash.h)

'''
expected=(w/'apps/xxhash/src/content/docs/v0-8-4/en/02-api/01-annotated.md').read_text().split('## Source and notices')[1];assert foot==expected
footer=(w/'apps/xxhash/src/content/docs/v0-8-4/ja/02-api/01-annotated.md').read_text().split('## 出典と通知')[1]
out=note/'drafts/ja/15-api-xxh3-impl.complete-unreviewed.md';assert not out.exists();out.write_text((prefix+body+'## 出典と通知'+footer).replace('/v0-8-4/en/','/v0-8-4/ja/'))
Path('/private/tmp/libx-xxh3-labels-521.json').write_text(json.dumps({'labels':{},'titles':titles},ensure_ascii=False,indent=2));print({'draft':str(out),'translatedNodes':len(used)})
