"""Save formal notice/configuration drafts. Does not create or approve an app."""
from pathlib import Path
from bs4 import BeautifulSoup
import json
N=Path(__file__).resolve().parent
C=json.loads((N/'CANDIDATE_DRAFT.json').read_text())
s=BeautifulSoup((N/'source/derived-manual.html').read_text(),'html.parser')
top=s.find(id='Top');copying=''.join(str(p)for p in top.find_all(['p','blockquote'],recursive=False))
fdl=s.find(id='GNU-Free-Documentation-License');assert fdl
for a in fdl.select('a[href]'):
 if a['href'].startswith('#'):a['href']='/docs/gnu-time/source/v1-10/manual.html'+a['href']
title='Libx GNU Time 1.10 User Guide / Libx GNU Time 1.10 利用ガイド'
notice='<section class="gnu-time-notices"><h3>'+title+'</h3><p>Original author: David MacKenzie. Original publisher: Free Software Foundation. Modification author and publisher: Libx.</p>'+copying+'<p>Copyright © 2026 Libx, for editing and independent Japanese translation. This modified guide is available under GNU Free Documentation License 1.3 or later, with no Invariant Sections, Front-Cover Texts, or Back-Cover Texts. No cover texts or invariant sections have been added.</p><h3>History / 履歴</h3><p>Original: GNU Time; version 1.10; document revision 13 February 2026; author David MacKenzie; publisher Free Software Foundation. Source: time-1.10.tar.xz, SHA256 '+C['sourceArchive']['sha256']+'.</p><p>2026: '+title+'. Modification author and publisher: Libx. Complete overview and chapters 1–2 in editable Markdown, static examples and independent unofficial Japanese translation. Original copyright, permission and whole English license retained. Modified 6 October 2026.</p></section>'
(N/'drafts/notice-context.json').write_text(json.dumps([{'kind':'source','html':notice+'<details class="gnu-time-license"><summary>Original English GNU Free Documentation License / 原英語GFDL全文</summary>'+str(fdl)+'</details>'}],ensure_ascii=False,indent=2)+'\n')
prefix='/docs/gnu-time/source/v1-10/'
links=[('manual.html','Fixed complete original manual','固定原文マニュアル全文'),('original/time-1.10.tar.xz','Unchanged original source archive','未変更の原著ソース配布物'),('original/doc/time.texi','Original editable Texinfo','編集可能な原Texinfo'),('original/doc/time.info','Original Info manual','原Infoマニュアル'),('source.zip','Editable source and rebuild kit','編集用原稿・再生成キット'),('SOURCE_README.md','Source and license notes','原稿とライセンスの案内')]
config={'paths':{'baseUrlPrefix':'/docs','projectSlug':'gnu-time','siteUrl':'https://libx.dev'},'language':{'default':'en','supported':['en','ja'],'displayNames':{'en':'English','ja':'日本語'}},'translations':{'en':{'displayName':'GNU Time User Guide','displayDescription':'GNU Time 1.10 complete user guide','categories':{'guide':'User guide','reference':'Original English notices'}},'ja':{'displayName':'GNU Time 利用ガイド','displayDescription':'GNU Time 1.10の全利用ガイドの原文・独自日本語訳','categories':{'guide':'利用ガイド','reference':'原英語の通知'}}},'versioning':{'versions':[{'id':'v1-10','name':'1.10','date':'2026-10-06T00:00:00Z','isLatest':True}]},'licensing':{'defaultSource':'gnu-time-manual','showAttribution':True,'sourceLanguage':'en','sources':[{'id':'gnu-time-manual','name':'GNU Time 1.10 manual, Overview and complete chapters 1–2','author':'David MacKenzie / Free Software Foundation','license':'GFDL1.3-or-later','licenseUrl':prefix+'manual.html#GNU-Free-Documentation-License','sourceUrl':'https://www.gnu.org/software/time/manual/','provenanceNotes':[{'en':'This unofficial Libx guide includes the complete overview and chapters 1–2 of GNU Time 1.10. The original English license is retained; the concept index is available in the fixed complete original manual, Info and Texinfo originals. Examples and reported values are original static samples, not Libx measurements. Program output and shell comments are retained; the comments distinguish bash/ksh from csh/tcsh.','ja':'Libxによる非公式ガイドです。GNU Time 1.10の原文概要・通知と第1〜2章全文を提供します。原英語のライセンスを保持し、概念索引は固定全文の英語マニュアル・Info・Texinfo原稿で参照できます。例と測定値は原著の静的な例で、Libxの実測値ではありません。プログラム出力と短いシェルコメントは原文保持です。例のコメントはbash/kshの場合とcsh/tcshの場合を区別しています。'},{'en':'Original copyright, permission, author, publisher, History and the whole original English GFDL are retained below. There are no Invariant Sections or Cover Texts.','ja':'原著作権・許諾・著作者・発行者・履歴・原英語GFDL全文を以下に保持しています。不変節・表紙文言はありません。'},{'en':'The document revision is 13 February 2026; the release date is 14 April 2026; the site date is acquisition 6 October 2026. Source fixed to the 1.10 archive SHA256 '+C['sourceArchive']['sha256']+'. Original sources are unmodified.','ja':'文書改訂日は2026年2月13日、リリース日は2026年4月14日、サイト版の日付は取得日の2026年10月6日です。原著1.10配布物SHA256 '+C['sourceArchive']['sha256']+'に固定しています。原著ソースは変更していません。'}],'attributionLinks':[{'url':prefix+p,'label':{'en':en,'ja':ja}}for p,en,ja in links]}]}}
(N/'drafts/project.config.jsonc').write_text(json.dumps(config,ensure_ascii=False,indent=2)+'\n')
print('GNU Time complete notice/English license/History/config drafts saved; formal adoption pending')
