from pathlib import Path
import re,json,hashlib,ast
note=Path('/Users/dolphilia/github/libx/docs/notes/document-import/xxhash/v0-8-4');p=json.loads((note/'API_TRANSLATION_DRAFT_PROGRESS.json').read_text());src=Path('/Users/dolphilia/github/libx')/p['draft']['path'];assert hashlib.sha256(src.read_bytes()).hexdigest()==p['draft']['sha256'];s=src.read_text();t=s.index('XXH3_64bits_reset_withSecretandSeed()</h2>');a=s.rfind('<a id=',0,t);t=s.index('XXH3_generateSecret()</h2>',a);b=s.rfind('<a id=',a,t);part=s[a:b]
m={}
for f in ['libx-xxh3-oneshot-509.py','libx-xxh3-state-510.py','libx-xxh3-stream-511.py']:
 tree=ast.parse(Path('/private/tmp/'+f).read_text());m.update(ast.literal_eval(next(n.value for n in tree.body if isinstance(n,ast.Assign)and any(isinstance(x,ast.Name)and x.id=='m'for x in n.targets))))
add={
'. Contract is identical.':'。契約は同一です。',
'Calculates 128-bit seeded variant of XXH3 hash of':'XXH3のシード付き128ビット版で、次の入力のハッシュを計算します：',
'The memory segment to be hashed, at least':'ハッシュを計算するメモリ領域。サイズは少なくとも',
'The secret used to alter hash result predictably.':'ハッシュ結果を予測可能な形で変化させるためのシークレット。',
', in bytes (must be &gt;= XXH3_SECRET_SIZE_MIN)':'（バイト単位。XXH3_SECRET_SIZE_MIN以上でなければなりません）',
': contract is the same.':'：契約は同じです。',
'Calculates the 128-bit hash of':'次の入力の128ビットハッシュを：','using XXH3.':'XXH3を使用して計算します。',
'The 64-bit seed to alter the hash\'s output predictably.':'ハッシュの出力を予測可能な形で変化させる64ビットのシード。',
'The memory between':'次の範囲のメモリ：',
'The calculated 128-bit XXH3 value.':'計算された128ビットのXXH3ハッシュ値。',
'Note: there was a bug in an earlier version of this function (&lt;= v0.8.2) that would make it generate an incorrect hash value when':'注記：この関数の以前の版（v0.8.2以前）には、次の条件で誤ったハッシュ値を生成するバグがありました：',
'== 0 and':'== 0、かつ',
'&lt; XXH3_MIDSIZE_MAX and':'&lt; XXH3_MIDSIZE_MAX、かつ',
'is different from':'が次の関数の生成するシークレットと異なる場合：',
'. As stated in the contract, the correct hash result must be the same as':'。契約に示されているとおり、正しいハッシュ結果は、次の関数と同じでなければなりません：',
'when':'（次の条件の場合）：',
'&lt;= XXH3_MIDSIZE_MAX. Results generated by this older version are wrong, hence not comparable.':'&lt;= XXH3_MIDSIZE_MAX。以前の版で生成された結果は誤っているため、比較できません。'}
m.update(add);parts=re.split(r'(<[^>]*>)',part);used=[]
for i in range(0,len(parts),2):
 x=parts[i].strip()
 if x in m:parts[i]=parts[i].replace(x,m[x]);used.append(x)
assert set(add)<=set(used),set(add)-set(used)
part=''.join(parts).replace('が <span class="tt">0</span>, <code class="param">','が <span class="tt">0</span> の場合、<code class="param">')
out=note/'drafts/ja/14-api-xxh3-family.combined-unreviewed.md';assert not out.exists();out.write_text(s[:a]+part+s[b:]);print({'draft':str(out),'translatedNodes':len(used),'functionsAdded':4,'wholePageCompleted':False})
