"""Seventh canonical step: disclose original utilities idle example discrepancy in footer."""
from pathlib import Path
import argparse,json,hashlib
arg=argparse.ArgumentParser();arg.add_argument('--repository',required=True);arg.add_argument('--workspace',required=True);arg.add_argument('--translation',action='store_true');a=arg.parse_args();root=Path(a.repository);packet=root/'docs/notes/document-import/libuv/1.53.0';app=Path(a.workspace)/'apps/libuv'
guide=(packet/'sources/docs/src/guide/utilities.rst').read_text();code=(packet/'sources/docs/code/idle-compute/main.c').read_text()
assert 'will now be called repeatedly' in guide and 'keep calling the idle callback again' in guide
assert 'uv_idle_stop(handle);' in code and 'uv_idle_start(&idler, crunch_away);' in code
assert (app/'public/source/v1-53-0/docs/code/idle-compute/main.c').read_bytes()==(packet/'sources/docs/code/idle-compute/main.c').read_bytes()
notes={'en': '<p>Libx editorial note on the original idle-compute example: the guide describes continuous calls to <code>crunch_away</code> between input events. The fixed example instead calls <code>uv_idle_stop(handle)</code> inside every <code>crunch_away</code> invocation to avoid overwhelming the terminal, and <code>on_type</code> restarts the idle handle after successful input. Original prose and snippets are retained; see the <a href="/docs/libuv/source/v1-53-0/docs/code/idle-compute/main.c">complete original example</a> for the actual stop/restart sequence.</p>', 'ja': '<p>原idle-compute例についてのLibx編集注記: ガイドは、入力イベントの間に<code>crunch_away</code>を連続して呼び出すと説明しています。一方、固定の例では、端末への出力過多を避けるために、<code>crunch_away</code>内で毎回<code>uv_idle_stop(handle)</code>を呼び出します。<code>on_type</code>は入力成功後にidleハンドルを再開します。原文と抜粋は保持しています。実際の停止・再開の順序は、<a href="/docs/libuv/source/v1-53-0/docs/code/idle-compute/main.c">原例の全文</a>を参照してください。</p>'}
for lang in ['en']+(['ja'] if a.translation else []):
 p=packet/('canonical/en/guide/utilities.md' if lang=='en' else 'translation/ja/guide/utilities.md');head,body=p.read_text().split('---\n',2)[1:];line=next(l for l in head.splitlines() if l.startswith('documentContext: '));contexts=json.loads(line.split(': ',1)[1]);editorial=next(c for c in contexts if c['kind']=='editorial')
 if notes[lang] not in editorial['html']:editorial['html']+=notes[lang]
 head=head.replace(line,'documentContext: '+json.dumps(contexts,ensure_ascii=False));p.write_text('---\n'+head+'---\n'+body);assert p.read_text().split('---\n',2)[2]==body;(app/('src/content/docs/v1-53-0/'+lang+'/guide/utilities.md')).write_bytes(p.read_bytes())
p=packet/'canonical/en/guide/utilities.md';body=p.read_text().split('---\n',2)[2];mp=packet/'CONTENT_MAP.json';m=json.loads(mp.read_text());row=next(r for r in m['rows'] if r['slug']=='guide/utilities');row['canonicalSha256']=hashlib.sha256(p.read_bytes()).hexdigest();assert row['bodySha256']==hashlib.sha256(body.encode()).hexdigest();m['canonicalGenerationSteps']=[f+' --repository ROOT --workspace WORKSPACE' for f in ['generate-canonical.py','apply-basics-editorial-note.py','apply-networking-declaration.py','apply-processes-editorial-note.py','apply-eventloops-editorial-note.py','apply-utilities-editorial-note.py','apply-utilities-idle-note.py']];m['utilitiesIdleOverlay']='Original continuous idle narrative vs example stop on every callback and restart after input; footer disclosure.';mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');print('utilities idle difference noted only footer; body/code unchanged')
