"""Apply source-discrepancy footer note after generate-canonical.py.
Original body/code stay exact. The note is deterministic and never inserted
in upstream source or body. This is a documented second canonical generation step.
"""
from pathlib import Path
import argparse,json,hashlib
arg=argparse.ArgumentParser();arg.add_argument('--repository',required=True);arg.add_argument('--workspace',required=True);a=arg.parse_args();root=Path(a.repository);packet=root/'docs/notes/document-import/libuv/1.53.0';app=Path(a.workspace)/'apps/libuv';p=packet/'canonical/en/guide/basics.md';text=p.read_text();head,body=text.split('---\n',2)[1:];line=next(l for l in head.splitlines() if l.startswith('documentContext: '));contexts=json.loads(line.split(': ',1)[1]);editorial=next(n for n in contexts if n['kind']=='editorial');marker='Libx editorial note on loop cleanup in the fixed guide'
note='<p>Libx editorial note on loop cleanup in the fixed guide: the prose says the examples never close loops, but all three included examples call <code>uv_loop_close</code>. See the fixed original <a href="/docs/libuv/source/v1-53-0/docs/code/helloworld/main.c">helloworld</a>, <a href="/docs/libuv/source/v1-53-0/docs/code/default-loop/main.c">default-loop</a>, and <a href="/docs/libuv/source/v1-53-0/docs/code/idle-basic/main.c">idle-basic</a> sources. Original prose and code are preserved; this note identifies their inconsistency.</p>'
for name in ['helloworld','default-loop','idle-basic']:
 original=packet/('sources/docs/code/'+name+'/main.c');assert 'uv_loop_close(' in original.read_text();assert (app/('public/source/v1-53-0/docs/code/'+name+'/main.c')).read_bytes()==original.read_bytes()
if marker not in editorial['html']:editorial['html']+=note
else:assert editorial['html'].endswith(note)
head=head.replace(line,'documentContext: '+json.dumps(contexts,ensure_ascii=False));updated='---\n'+head+'---\n'+body;assert updated.split('---\n',2)[2]==body;p.write_text(updated);(app/'src/content/docs/v1-53-0/en/guide/basics.md').write_bytes(p.read_bytes());m=json.loads((packet/'CONTENT_MAP.json').read_text());row=next(r for r in m['rows'] if r['slug']=='guide/basics');row['canonicalSha256']=hashlib.sha256(p.read_bytes()).hexdigest();assert row['bodySha256']==hashlib.sha256(body.encode()).hexdigest();m['canonicalGenerationSteps']=['generate-canonical.py --repository ROOT --workspace WORKSPACE','apply-basics-editorial-note.py --repository ROOT --workspace WORKSPACE'];m['editorialOverlay']='Fixed source paragraph disagrees with all3 included loop-close examples; note in footer only; original body/code unchanged.';(packet/'CONTENT_MAP.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');print('basics canonical footer note applied; original body/code unchanged')
