"""Sixth canonical step: disclose original utilities/API discrepancies in footer."""
from pathlib import Path
import argparse,json,hashlib
arg=argparse.ArgumentParser();arg.add_argument('--repository',required=True);arg.add_argument('--workspace',required=True);arg.add_argument('--translation',action='store_true');a=arg.parse_args();root=Path(a.repository);packet=root/'docs/notes/document-import/libuv/1.53.0';app=Path(a.workspace)/'apps/libuv'
guide=(packet/'sources/docs/src/guide/utilities.rst').read_text();header=(packet/'sources/include/uv.h').read_text();timer=(packet/'sources/docs/src/timer.rst').read_text();thread=(packet/'sources/docs/src/threadpool.rst').read_text()
assert 'uv_timer_set_repeat(uv_timer_t *timer, int64_t repeat)' in guide
assert 'uv_timer_set_repeat(uv_timer_t* handle, uint64_t repeat)' in header and 'uv_timer_set_repeat(uv_timer_t* handle, uint64_t repeat)' in timer
assert 'returns -1' in guide and 'before it returns\n    UV_EINVAL' in timer
assert 'void ftp_cleanup(uv_work_t *req)' in guide
assert 'uv_after_work_cb)(uv_work_t* req, int status)' in header and 'uv_after_work_cb)(uv_work_t* req, int status)' in thread
for f in ['include/uv.h','docs/src/guide/utilities.rst','docs/src/timer.rst','docs/src/threadpool.rst']:assert (app/'public/source/v1-53-0'/f).read_bytes()==(packet/'sources'/f).read_bytes()
notes={
'en':'<p>Libx editorial note on the fixed guide: the original utilities chapter uses <code>int64_t repeat</code> for <code>uv_timer_set_repeat</code>, whereas the fixed 1.53.0 header and API use <code>uint64_t repeat</code>. It describes <code>uv_timer_again</code> as returning -1 for a never-started timer; the fixed API specifies <code>UV_EINVAL</code>. Its <code>ftp_cleanup</code> example takes only <code>uv_work_t* req</code>, whereas the fixed <code>uv_after_work_cb</code> also takes <code>int status</code>. Original text and example code are retained. See the fixed <a href="/docs/libuv/v1-53-0/en/reference/timer/">timer API</a>, <a href="/docs/libuv/v1-53-0/en/reference/threadpool/">threadpool API</a> and <a href="/docs/libuv/source/v1-53-0/include/uv.h">original uv.h</a> for fixed-version declarations and return values.</p>',
'ja':'<p>固定ガイドについてのLibx編集注記: 原utilities章は<code>uv_timer_set_repeat</code>の引数を<code>int64_t repeat</code>としていますが、固定1.53.0のヘッダーとAPIでは<code>uint64_t repeat</code>です。また、開始したことがないタイマーでの<code>uv_timer_again</code>の戻り値を-1と説明していますが、固定APIでは<code>UV_EINVAL</code>です。原例の<code>ftp_cleanup</code>は<code>uv_work_t* req</code>だけを受け取りますが、固定版の<code>uv_after_work_cb</code>には<code>int status</code>も必要です。原文と例のコードは保持しています。固定版の宣言と戻り値は、<a href="/docs/libuv/v1-53-0/en/reference/timer/">timer API</a>、<a href="/docs/libuv/v1-53-0/en/reference/threadpool/">threadpool API</a>、<a href="/docs/libuv/source/v1-53-0/include/uv.h">原uv.h全文</a>を参照してください。</p>'}
for lang in ['en']+(['ja'] if a.translation else []):
 p=packet/('canonical/en/guide/utilities.md' if lang=='en' else 'translation/ja/guide/utilities.md');head,body=p.read_text().split('---\n',2)[1:];line=next(l for l in head.splitlines() if l.startswith('documentContext: '));contexts=json.loads(line.split(': ',1)[1]);editorial=next(c for c in contexts if c['kind']=='editorial')
 if notes[lang] not in editorial['html']:editorial['html']+=notes[lang]
 head=head.replace(line,'documentContext: '+json.dumps(contexts,ensure_ascii=False));p.write_text('---\n'+head+'---\n'+body);assert p.read_text().split('---\n',2)[2]==body;(app/('src/content/docs/v1-53-0/'+lang+'/guide/utilities.md')).write_bytes(p.read_bytes())
p=packet/'canonical/en/guide/utilities.md';body=p.read_text().split('---\n',2)[2];mp=packet/'CONTENT_MAP.json';m=json.loads(mp.read_text());row=next(r for r in m['rows'] if r['slug']=='guide/utilities');row['canonicalSha256']=hashlib.sha256(p.read_bytes()).hexdigest();assert row['bodySha256']==hashlib.sha256(body.encode()).hexdigest();m['canonicalGenerationSteps']=[f+' --repository ROOT --workspace WORKSPACE' for f in ['generate-canonical.py','apply-basics-editorial-note.py','apply-networking-declaration.py','apply-processes-editorial-note.py','apply-eventloops-editorial-note.py','apply-utilities-editorial-note.py']];m['utilitiesEditorialOverlay']='Original repeat argument type, timer-again failure return, cleanup callback arity retained; fixed header/API differences only footer.';mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');print('utilities original/API differences noted only footer; body/code unchanged')
