"""Eighth canonical step: clarify request cancellation lifetime in footer."""
from pathlib import Path
import argparse,json,hashlib
arg=argparse.ArgumentParser();arg.add_argument('--repository',required=True);arg.add_argument('--workspace',required=True);arg.add_argument('--translation',action='store_true');a=arg.parse_args();root=Path(a.repository);packet=root/'docs/notes/document-import/libuv/1.53.0';app=Path(a.workspace)/'apps/libuv';source=packet/'sources/docs/src/request.rst';text=source.read_text();assert "not** safe to free the memory associated with the request until the" in text and 'callback is called.' in text;assert (app/'public/source/v1-53-0/docs/src/request.rst').read_bytes()==source.read_bytes()
notes={'en':'<p>Libx editorial clarification on request lifetime: the original design overview describes requests as closed on completion or cancellation. Cancellation does not permit immediate memory release: the fixed <a href="/docs/libuv/v1-53-0/en/reference/request/#c.uv_cancel">uv_cancel API</a> states that a cancelled request receives its callback later, and its memory must not be freed before that callback. Original wording is retained; see the <a href="/docs/libuv/source/v1-53-0/docs/src/request.rst">fixed request source</a>.</p>','ja':'<p>リクエストの寿命についてのLibx編集補足: 原設計概要は、リクエストが完了時またはキャンセル時に閉じられると説明しています。キャンセル直後にメモリーを解放できるという意味ではありません。固定版の<a href="/docs/libuv/v1-53-0/en/reference/request/#c.uv_cancel">uv_cancel API</a>は、キャンセルしたリクエストのコールバックが後で呼ばれ、それより前にメモリーを解放してはならないと明記しています。原文は保持しています。<a href="/docs/libuv/source/v1-53-0/docs/src/request.rst">固定request原文</a>も参照してください。</p>'}
for lang in ['en']+(['ja'] if a.translation else []):
 p=packet/('canonical/en/reference/design.md' if lang=='en' else 'translation/ja/reference/design.md');head,body=p.read_text().split('---\n',2)[1:];line=next(l for l in head.splitlines() if l.startswith('documentContext: '));ctx=json.loads(line.split(': ',1)[1]);edit=next((c for c in ctx if c['kind']=='editorial'),None)
 if edit is None:
  edit={'kind':'editorial','html':'<p>原画像指定の倍率・配置・代替テキストを復元するため、ディレクティブのインデントだけを修正しました。固定PNGとテキスト図の原ソースは変更していません。</p>'};ctx.append(edit)
 if notes[lang] not in edit['html']:edit['html']+=notes[lang]
 head=head.replace(line,'documentContext: '+json.dumps(ctx,ensure_ascii=False));p.write_text('---\n'+head+'---\n'+body);assert p.read_text().split('---\n',2)[2]==body;(app/('src/content/docs/v1-53-0/'+lang+'/reference/design.md')).write_bytes(p.read_bytes())
p=packet/'canonical/en/reference/design.md';body=p.read_text().split('---\n',2)[2];mp=packet/'CONTENT_MAP.json';m=json.loads(mp.read_text());row=next(x for x in m['rows'] if x['slug']=='reference/design');row['canonicalSha256']=hashlib.sha256(p.read_bytes()).hexdigest();assert row['bodySha256']==hashlib.sha256(body.encode()).hexdigest();m['canonicalGenerationSteps']=[f+' --repository ROOT --workspace WORKSPACE' for f in ['generate-canonical.py','apply-basics-editorial-note.py','apply-networking-declaration.py','apply-processes-editorial-note.py','apply-eventloops-editorial-note.py','apply-utilities-editorial-note.py','apply-utilities-idle-note.py','apply-design-editorial-note.py']];m['designEditorialOverlay']='Original cancellation wording retained; fixed API callback-before-memory-free rule clarified only footer.';mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');print('design cancellation memory lifetime clarification only footer; original body retained')
