"""Install check:content after prepare-runtime; do not change document text."""
from pathlib import Path
import argparse,json,shutil,hashlib
p=argparse.ArgumentParser();p.add_argument('--repository',required=True);p.add_argument('--workspace',required=True);a=p.parse_args();root=Path(a.repository);w=Path(a.workspace);rel=Path('docs/notes/document-import/libuv/1.53.0');f=w/'apps/libuv/package.json';pkg=json.loads(f.read_text());assert pkg['name']=='apps-libuv';pkg['scripts']['check:content']='python3 ../../docs/notes/document-import/libuv/1.53.0/check-content.py';f.write_text(json.dumps(pkg,ensure_ascii=False,indent=2)+'\n');dest=w/rel/'check-content.py';dest.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(root/rel/'check-content.py',dest);print('read-only check:content installed; no content touched')
classification=json.loads((root/rel/'SOURCE_CLASSIFICATION.json').read_text())
for entry in classification['generatedInputs']:
 assert entry['originalPath']=='docs/src/sphinx-plugins/__pycache__/manpage.cpython-312.pyc'
 cache=w/'apps/libuv/public/source/v1-53-0'/entry['originalPath']
 if cache.exists():
  assert hashlib.sha256(cache.read_bytes()).hexdigest()==entry['sha256'];cache.unlink()
print('Historical generated bytecode is retained as acquisition evidence, excluded from published originals')
