from pathlib import Path
import json,hashlib,os
N=Path(__file__).resolve().parent;P=N.parents[1];W=P.parents[4];A=W/'apps/gnu-sed';assert os.environ.get('LIBX_UPDATE_WORKSPACE')==str(W);h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();line=next(x for x in(A/'src/content/docs/v4-10/en/01-guide/19-sed-regular-expressions.md').read_text().splitlines()if x.startswith('documentContext: '));context=json.loads(line.removeprefix('documentContext: '));assert len(context)==1;raw=context[0]['html'];assert 'Modified6October2026' in raw
pairs=[('User Guide — Chapters 1–5','User Guide — Chapters 1–6'),('利用ガイド — 第1〜5章','利用ガイド — 第1〜6章')];old=raw
for a,b in pairs:assert a in raw;raw=raw.replace(a,b,1)
entry='<p>7 October 2026: Libx GNU sed 4.10 User Guide — Chapters 1–6 / Libx GNU sed 4.10 利用ガイド — 第1〜6章. Modification author and publisher: Libx. Added complete chapter 6 with its complete referenced footnote8, with independent Japanese translation and static original expressions and references. The previously published Chapters 1–5 text is retained; original archive, permission, authors and full English GFDL are preserved.</p>';assert raw.count('</section>')==1;raw=raw.replace('</section>',entry+'</section>');inverse=raw.replace(entry,'',1)
for a,b in pairs:inverse=inverse.replace(b,a,1)
assert inverse==old;context[0]['html']=raw;(N/'DOCUMENT_CONTEXT.json').write_text(json.dumps(context,ensure_ascii=False,indent=2)+'\n');rows=[]
for row in json.loads((N/'CANONICAL_BINDING.json').read_text())['rows']:
 p=W/row['path'];s=p.read_text();assert 'documentContext:'not in s;front,body=s.split('---',2)[1:];front=front.strip()+'\ndocumentId: '+json.dumps('gnu-sed:4.10:'+Path(row['id']).stem)+'\nlicenseSource: "gnu-sed-manual"\ntoc: {"maxLevel": 4}\ndocumentContext: '+json.dumps(context,ensure_ascii=False)+'\n';out='---\n'+front+'---'+body
 for dest in [p,A/'src/content/docs/v4-10'/row['language']/row['id'],A/'public/source/v4-10/edited'/row['language']/row['id']]:dest.write_text(out)
 assert out.split('---',2)[2]==body;rows.append({'id':row['id'],'language':row['language'],'canonicalSHA256':h(p),'bodyUnchanged':True})
p=A/'src/config/project.config.jsonc';config=json.loads(p.read_text());config['translations']['en'].update(displayName='GNU sed User Guide',displayDescription='GNU sed4.10 complete chapters1–6');config['translations']['en']['categories']['guide']='User guide';config['translations']['ja'].update(displayName='GNU sed 利用ガイド',displayDescription='GNU sed4.10第1〜6章全文の原文と独自日本語訳');config['translations']['ja']['categories']['guide']='利用ガイド';source=config['licensing']['sources'][0];source['name']=source['name'].replace('chapters1–5','chapters1–6');source['provenanceNotes'][0]={'en':'This unofficial Libx guide includes complete chapters1–6 and all eight referenced footnotes from GNU sed4.10. Remaining chapters and indexes are supplied in the fixed complete English manual, Texinfo and Info originals.','ja':'Libxによる非公式ガイドです。GNU sed4.10の第1〜6章全文と参照脚注8件を収録しています。残りの章と索引は、固定全文の英語マニュアル・Texinfo・Info原稿を参照できます。'};source['provenanceNotes']=[v for v in source['provenanceNotes']if not v['en'].startswith('Chapter6 was added')];source['provenanceNotes'].append({'en':'Chapter6 was added on7October2026, including complete footnote8 and original static examples. Existing Chapters1–5 retain their previous preferred text and modification history.','ja':'2026年10月7日に第6章を追加し、脚注8全文と原文の静的な例を収録しました。既存の第1〜5章の定本文と変更履歴は保持しています。'});source['provenanceNotes']=[v for v in source['provenanceNotes']if not v['en'].startswith('Original TODO markers')];source['provenanceNotes'].append({'en':'Original TODO markers, spelling and examples are retained as static source text; consult the fixed complete original for details.','ja':'原文のTODO・表記・例は静的な原文として保持しています。詳しくは固定した原典全文を参照してください。'});p.write_text(json.dumps(config,ensure_ascii=False,indent=2)+'\n');(N/'CONTEXT_BINDING.json').write_text(json.dumps({'status':'saved-context-body-unchanged','documents':14,'oldWholeLicenseNoticeContextRecoveredExactlyByInverse':True,'contextSHA256':h(N/'DOCUMENT_CONTEXT.json'),'siteConfigSHA256':h(p),'rows':rows,'meaningReview':'Body review retained; title/scope/history delta requires separate reading'},indent=2)+'\n');print('New14notice/context added;old65MD retained;sourcekit pending')

# Publish the updated scope after the original chapter1–3 generator.
readme=N/"SOURCE_OFFER_README.md"
assert readme.is_file()
(A/"public/source/v4-10/SOURCE_README.md").write_bytes(readme.read_bytes())
