from pathlib import Path
from bs4 import BeautifulSoup
import json,hashlib,datetime
R=Path('/Users/dolphilia/github/libx');N=R/'docs/notes/document-import/gnu-ed/v1-22-5';h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();s=BeautifulSoup((N/'source/derived-manual.html').read_bytes(),'html.parser',from_encoding='iso-8859-15');top=s.find(id='Top');rows=[]
blocks=[('Top','01-overview-notice')]+[(x.get('id'),f'{i+2:02d}-'+x.get('id').lower().replace('_0027','').replace('-','-')) for i,x in enumerate(s.select('.chapter-level-extent')) if x.get('id')!='GNU-Free-Documentation-License']
for node,slug in blocks:
 original=s.find(id=node)
 if node=='Top':body=''.join(str(c)for c in original.find_all(['h1','p','blockquote'],recursive=False))
 else:
  x=BeautifulSoup(str(original),'html.parser')
  for nav in x.select('.nav-panel'):nav.decompose()
  body=str(x)
 dest=N/'drafts/en'/(slug+'.body.html');dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(body+'\n',encoding='utf8');v=BeautifulSoup(body,'html.parser');assert '\ufffd' not in v.get_text();rows.append({'slug':slug,'sourceNode':node,'titleEN':v.find(['h1','h2']).get_text(' ',strip=True),'EnglishDraftPath':str(dest.relative_to(N)),'sha256':h(dest),'words':len(v.get_text().split()),'pre':len(v.select('pre')),'var':len(v.select('var')),'table':len(v.select('table')),'JapaneseDraft':False,'meaningReview':'pending'})
p=N/'drafts/reference/gfdl.body.html';p.parent.mkdir(parents=True,exist_ok=True);p.write_text(str(s.find(id='GNU-Free-Documentation-License'))+'\n');proof={'schemaVersion':1,'status':'candidate-source-scope-prepared-not-selected','at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'version':'1.22.5','documentRevision':'6 February 2026','officialURL':'https://www.gnu.org/software/ed/','officialManualURL':'https://www.gnu.org/software/ed/manual/ed_manual.html','archiveSHA256':h(N/'source/ed-1.22.5.tar.lz'),'documentLicense':'GFDL1.3-or-later','InvariantSections':False,'CoverTexts':False,'copyright':'1993,1994,2006–2026 Free Software Foundation','authors':['Andrew L. Moore','François Pinard','Antonio Diaz Diaz'],'preservedSourceEncoding':'ISO-8859-15; generated HTML declares matching charset, UTF-8 drafts decoded without replacement characters','scope':'Top and all11complete manual chapters. Original complete GFDL in English reference, fullmanual/Info/Texinfo/archive preserved; website excluded.','proposedScope':{'pagesPerLanguage':len(rows),'rows':rows,'EnglishOnlyLicense':{'path':str(p.relative_to(N)),'sha256':h(p)},'words':sum(x['words'] for x in rows),'pre':sum(x['pre']for x in rows),'var':sum(x['var']for x in rows)},'JapaneseComparison':{'referenceURL':'https://linuxjm.sourceforge.io/html/GNU_ed/man1/ed.1.html','savedEvidence':'docs/notes/project-expansion/runs/evidence/2026-10-06-931/linuxjm-ed.html','observedScope':'Japanese man page updated2022/02; commands synopsis/options only, explicitly directs readers to info ed for fullmanual','additionalValueHypothesis':'Same fixed1.22.5 fulltutorial, addressing, regex, commands and substitute conditions in Japanese; existing Japanese man useful but narrower. Do not claim absence of other Japanese materials.','searchStatus':'limited search performed; further specific comparison/score and separate selection review pending'},'fulfillmentPlan':'Preserve authors/copyright/title/GFDL notice/fullEnglishlicense; History and publisher/modificationdate; exact editableEnglish/Japanese source and original preferredTexinfo in sourceZIP; footer original links/editorial limits. No fallbacksoftwarelicense needed for manual.','originalExamplesExecuted':False,'adopted':False,'formalAppCreated':False,'remaining':['representative native rendering/code/link conversion validation','additionalValue/practicality scoring with fixed evidence','separate selection review and ledger registration','Japanese drafts/whole meaning review','formal sourceoffer/build/integration/publication']}
(N/'CANDIDATE_DRAFT.json').write_text(json.dumps(proof,ensure_ascii=False,indent=2)+'\n');(N/'PROGRESS.json').write_text(json.dumps({'state':'candidate-scope-prepared','publication':'not-ready','eligible':False,'appCreated':False,'EnglishDrafts':len(rows),'JapaneseDrafts':0,'reviewedPages':0,'nextAction':'固定1.22.5全11章+Top原文草稿12と明示GFDL条件を保持し、現行日本語資料追加照合・代表静的変換/build/display→採点/別パス選定へ。最新公開ベースから正式appを作る前に上限と全必須条件を照合。原文技術監査は広げない。'},ensure_ascii=False,indent=2)+'\n');print(json.dumps({'pages':len(rows),'words':proof['proposedScope']['words'],'pre':proof['proposedScope']['pre'],'selected':False}))
